### ISSUE TITLE
Error with first binding in html after ugrading to v2.0

### ISSUE THREAD

**Issue by ZiadJ** [Knockout-Contrib/KoGrid#132]
After upgrading to v2.0 I get the following error:

Unhandled exception at line 1930, column 17 in http://localhost:59069/Scripts/knockout-2.2.0.debug.js
0x800a139e - Microsoft JScript runtime error: Unable to parse bindings.
Message: ReferenceError: 'searchText' is undefined;
Bindings value: with: searchText

The error occurs when the datasource is populated and is always associated with the first ko binding in my html starting from the top. In my case it is 'searchText' and it is not wired with to koGrid in any way. So how it made an association is beyond me.

After switching back to v1.3 the error was gone.

**Comment by davidjsilva** [comment]
I had a similar issue.  Do you by chance use your own custom cell templates?  Because in 2.0 the way it's done has changed.  Whereas before you'd provide the id of the template, now it expects you to provide the template html in a string.  If you provide an id of the template then it will cause knockout to use Window as the binding context and that's way its trying to bind to 'searchText' which is not even in your koGrid.  Hope that helps.

**Comment by ZiadJ** [comment]
Wieeww...that was quick!
Yes I have custom templates all over the place so that must be it. Is this mentioned anywhere in the docs? Else can you send me a sample for the new template. I'm a bit confused on how to provide it in a string.

**Comment by davidjsilva** [comment]
@ZiadJ I don't know if it's in the docs, probably not, but I learned this the while debugging the code.  So basically when creating the column definitions where before you would probably do something like cellTemplate: '#SomeTemplateId' now you need to do cellTemplate: '<div>some template html</div>'.  Hope that helps.

**Comment by orneryd** [comment]
the celltemplate documentation should explain the changes. https://github.com/ericmbarnard/KoGrid/wiki/About-Custom-Templates

The reason we changed it is that templates were being handled terribly before. Knockout, unfortunately, does not have a robust temple system for this. 

In older versions kogrid was actually appending the dom with a bunch of script tags just so it could handle its own templates. what we did is changed the build files to be html that compiles down into a string and just use jquery to perform the tranformation from string to element.

I also wanted to get away from the ko-grid specific syntax and get rid of string the find and replace that was happening by using $cell and $cellValue, etc..

 this also makes it easier to use fields that are nested in your datamodel (like: model.name.first, or model.amount.min etc...) and using cellFormatter (or cellFilter) which is a function that gets called and transforms your data without using a template. they operate exactly liek Angularjs' "filters" but instead of it being applied to the dom (because there are no "filters" in knockout), it gets called if you use the getProperty method
