### ISSUE TITLE
Update Item in Grid

### ISSUE THREAD

**Issue by erikbcox** [Knockout-Contrib/KoGrid#172]
http://jsfiddle.net/Dt3nw/10/

In the above example I can select an item by clicking on the name, then change the age in the box below. How do I trigger a change of the text in the grid itself? Per the wiki there was  watchDataItems config variable that seemed to allow this in the past. 

I guess it would likely work to update the data and rebind the whole grid but that doesn't seem like it is in the spirit of knockout binding.

**Comment by orneryd** [comment]
I know this works. 

http://jsfiddle.net/timothyswt/Dt3nw/11/

and because I knew that worked, I tried this:

``` javascript
    self.confirm = function(){
        self.myData.valueHasMutated();
        self.selectedItem({});
    };
```

the grid doesn't know the value has updated becuase they are two different observables. If you update the data and you want it to be reflected int he grid you need to call valueHasMutated() on the data array. It will update the grid,

**Comment by erikbcox** [comment]
http://jsfiddle.net/Dt3nw/13/ - Updated with your change and it worked like a charm. Thanks!
