### ISSUE TITLE
2.0 Release Discussion

### ISSUE THREAD

**Issue by ericmbarnard** [Knockout-Contrib/KoGrid#77]
So from a work perspective... I think we need to plan the following:
1. Update our ko reference to the RC
2. Finalize the new Grid Class/Binding Handler architecture (me)
3. Clean up all event handlers and try to refactor them into the new grid classes
4. Build out "plugin" system
5. Cherry pick some new features and work them in

yes - refactor, not clean slate

**Comment by orneryd** [comment]
We should probably finalize the propertyPath branch before merging in the re-arch since i made minor changes to a lot of files to refactor the utils class. (no more global "utils" it's all under 'ko.utils' or' kg.utils')

For the 2.0 release I would really like to see the following issues resolved: #3, #6, #7, #15, #23, #24, #35, #43, #44 (I already have a working implementation not checked in), #46, #54, #58, and #76. I added them to the 2.0 release milestone but that is totally open to discussion.

**Comment by ericmbarnard** [comment]
I've looked through the ones you have listed and agree.

Along with those, I'll add some issues to the points listed above and create those for the 2.0 milestone. Then I guess we'll plow forward with getting things implemented

**Comment by orneryd** [comment]
I have completely rewritten kogrid since I ported this to angular. the new version can be found here https://github.com/angular-ui/ng-grid/tree/knockout 

It is still a WIP but nearing completion. But essentially its a complete rewrite to take advantage of knockout's inherent capabilities and reduce the code footprint by 40%. It is currently not backwards compatible with the current implementations of koGrid.  Tests will likely need to be re-written.

Once its completed you will need to rename all the namespaces, do any backwards compatibility modifications you see fit to do, update unit tests and merge it all into main, :)

**Comment by davidjsilva** [comment]
@timothyswt so does this mean that the 2.0 release for kogrid has halted?

**Comment by orneryd** [comment]
No, it hasn't halted. In fact it should be done here very soon.

**Comment by davidjsilva** [comment]
OK great that's good to hear!

**Comment by orneryd** [comment]
closing in favor of PR 124.
