### ISSUE TITLE
issue with loading kogrid with data

### ISSUE THREAD

**Issue by mghz** [Knockout-Contrib/KoGrid#90]
I was trying to use the grid in my app but did not work. 

I tried the getting started example with jsfiddle and it did not work. Here's a link: http://jsfiddle.net/mar1ghz/NMtsX/4/

I added the knockout and kogrid as recourses with jquery as the framework.

**Comment by orneryd** [comment]
couple of problems with your fiddle. 

the kogrid js file was added from the blob section and not from the raw:
https://github.com/ericmbarnard/KoGrid/blob/master/build/KoGrid.debug.js (check console for script errors.)
vs
https://raw.github.com/ericmbarnard/KoGrid/master/build/KoGrid.debug.js (yay works!)
no css file was added as a resource, (zomg! the grid will look like crap without this. but jsFiddle has an issue with adding CSS files as a resource at the moment so you need to copy it into the style section)

I updated your fiddle: http://jsfiddle.net/NMtsX/11/

**Comment by mghz** [comment]
Thank you for the prompt reply,

Thank you for the tip on using the raw source from github. I added the proper urls under "managed resources". I tried the fiddle you provided but I still can't run and the grid won't display.  I created a new one with a vm I'm trying to use and i can't get the grid to display. I don't mind the non css styles I just want something displayed first. 

In my code the issue I'm having is with this line: koGrid: { data: children, autoGenerateColumns: true } ... any view model property I set here does not work. I tried, vm.children, $root.children but none worked either. Does my model have to be defined as an object literal instead of a function for this to work?

this is the new fiddle: http://jsfiddle.net/mar1ghz/erYZ4/14/

**Comment by orneryd** [comment]
my fiddle http://jsfiddle.net/NMtsX/11/ in chrome and firefox
http://i.imgur.com/LjbjS.png

IE is having issues with jsfiddle, not with kogrid.
SCRIPT438: Object doesn't support property or method 'getStyle' 
LayoutCM.js, line 195 character 5
SEC7113: CSS was ignored due to mime type mismatch 
KoGrid.css
SEC7112: Script from https://raw.github.com/SteveSanderson/knockout/master/build/output/knockout-latest.debug.js was blocked due to mime type mismatch 
show
SEC7112: Script from https://raw.github.com/ericmbarnard/KoGrid/master/build/KoGrid.debug.js was blocked due to mime type mismatch 
show
SCRIPT5009: 'ko' is undefined 
show, line 407 character 1

**Comment by orneryd** [comment]
as for your fiddle:
http://jsfiddle.net/mar1ghz/erYZ4/14/

`ko.applyBinding(new vm(data));​`
should be:
`ko.applyBindings(new vm(data));​`
and you are still missing the CSS.
https://raw.github.com/ericmbarnard/KoGrid/master/KoGrid.css

i updated your fiddle
http://jsfiddle.net/erYZ4/15/

**Comment by HSG-PSG-1** [comment]
Hi Tim,
I was looking for a demo and tried your last fiddle link - http://jsfiddle.net/erYZ4/15/
Doesn't work in IE or FF - says "ko is not defined" - does it need to be fixed?
